<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIzvtfcY\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIzvtfcY/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIzvtfcY.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIzvtfcY\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIzvtfcY\App_KernelDevDebugContainer([
    'container.build_hash' => 'IzvtfcY',
    'container.build_id' => 'fe993b57',
    'container.build_time' => 1740764392,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIzvtfcY');
